name: AI-based PR Reviewer & Summarizer with Chat Capabilities

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4       # <-- 添加这个步骤就行了
        with:
          fetch-depth: 0                # <-- 重要，确保所有文件历史都被checkout下来

      - uses: coderabbitai/ai-pr-reviewer@1.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
